name: "Test Operate Installation E2E"
on:
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  test:
    continue-on-error: False
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, macos-14]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
          node-version: "20.11"
    - name: Setup
      run:  |
        yarn
        # Uninstall brew
        sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
    - name: Run Test
      run: |
        node electron/test.js
